apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Msocial123/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://test-aks-c-test-lab-d2e14a-2a4f9cay.hcp.eastus.azmk8s.io:443
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
